language: elixir
services:
  - postgresql
addons:
  postgresql: "9.4"
elixir:
  - 1.4
  - 1.3
otp_release:
  - 20.0
  - 19.3
  - 18.3
matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.0
notifications:
  email: false
sudo: false
script:
  - mix test
